site_name: IHC 2026.1 - Grupo 11
site_url: https://unb-ihc.github.io/IHC_2026.1_Grupo11/
repo_url: https://github.com/UnB-IHC/IHC_2026.1_Grupo11
repo_name: UnB-IHC/IHC_2026.1_Grupo11

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: pt-BR
  palette:
    scheme: default
    primary: indigo
    accent: orange
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
    - content.code.copy

nav:
  - Início: index.md
  - Guia de Acessibilidade:
    - Introdução: guia_acessibilidade/apresentacaoGuia.md
    - Pesquisa de UX: guia_acessibilidade/ux_pesquisa.md
    - Estratégia de Serviço: guia_acessibilidade/estrategia_servico.md
    - Gestão de Projetos: guia_acessibilidade/gestaoProjetos.md
    - Heurísticas: guia_acessibilidade/heuristicas.md
    - Desenvolvimento Web: guia_acessibilidade/desenvolvimentoWeb.md
    - Design de Interface e UX: guia_acessibilidade/design.md
    - Conteúdo e Comunicação: guia_acessibilidade/geracaoConteudo.md
    - Formulários, Entrada de Dados e Prevenção de Erros: guia_acessibilidade/form.md
  - Aplicação do Guia e Ferramentas: aplicacao_guia/aplicacao-guia.md
  - Teste de Usabilidade: 
    - Introdução: teste_usabilidade/teste-usabilidade.md
    - Roteiro de Tarefas: teste_usabilidade/roteiro-tarefas.md
    - Perfil de Usuário: teste_usabilidade/perfil-user.md
    - Participantes: teste_usabilidade/participantes.md
    - Procedimentos: teste_usabilidade/procedimentos.md
    - Formulário SUS: teste_usabilidade/form-sus.md
    - Métricas de Usabilidade: teste_usabilidade/metricas-usabilidade.md
    - Referências: teste_usabilidade/referencias.md

  - Ferramentas:
      - Introdução: ferramentas/introducao.md
      - Ferramentas de Acessibilidade:
        - VLibras: ferramentas/vlibras.md
        - Acess Monitor Plus: ferramentas/acessMonitorPlus.md
        - ASES: ferramentas/ases.md
        - WAVE: ferramentas/wave.md
        - Lighthouse: ferramentas/lighthouse.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
