site_name: IHC 2026.1 - Grupo 11
site_url: https://unb-ihc.github.io/IHC_2026.1_Grupo11/
repo_url: https://github.com/UnB-IHC/IHC_2026.1_Grupo11
repo_name: UnB-IHC/IHC_2026.1_Grupo11

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: pt-BR
  palette:
    scheme: default
    primary: indigo
    accent: orange
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
    - content.code.copy

nav:
  - Início: index.md
  - Guia de Acessibilidade:
    - Desenvolvimento Web: guia_acessibilidade/desenvolvimentoWeb.md
    - Design de Interface e UX: guia_acessibilidade/design.md
    - Conteúdo e Comunicação: guia_acessibilidade/geracaoConteudo.md
    - Formulários, Entrada de Dados e Prevenção de Erros: guia_acessibilidade/form.md
  - Aplicação do Guia e Ferramentas: aplicacao_guia/aplicacao-guia.md
  - Teste de Usabilidade: teste_usabilidade/teste-usabilidade.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
